export const CASE_EVENT_TYPES = [
  "PAYMENT_FAILED",
  "RISK_CALCULATED",
  "AI_DECISION_CREATED",
  "POLICY_ALLOWED",
  "POLICY_REJECTED",
  "WORKFLOW_STARTED",
  "WHATSAPP_SENT",
  "EMAIL_SENT",
  "PAYMENT_RETRY_STARTED",
  "PAYMENT_SUCCEEDED",
  "RECOVERY_RECORDED",
  "HUMAN_TASK_CREATED",
  "HUMAN_DECISION_RECORDED",
  "CASE_PAUSED",
  "CASE_RESUMED",
  "CASE_ESCALATED",
  "CASE_STOPPED",
] as const;

export type CaseEventType = (typeof CASE_EVENT_TYPES)[number];
